name: André Meyerjürgens
description: "Blog von André Meyerjürgens"
url: "http://blog.daxtero.de"

paginate: 10

timezone: Europe/Berlin
date_format: '%Y-%m-%d %H:%M:%S'
download_images: True

markdown: redcarpet
pygments: true

include: ['.htaccess']
exclude: ['blog.daxtero.de.iml']